### ISSUE TITLE
feat: Logout

### ISSUE THREAD

**Issue by callumcurtis** [restauwants/restauwants#10]
### Describe the feature you'd like to request

As a user, I want to be able to logout, so that I can change accounts.

### Describe the solution you'd like to see

On the profile page, there should be a button that allows the user to sign out. There should also be a confirmation step that ensures that the user doesn't accidentally press the button.

**Comment by camrohwer** [comment]
Ability to logout from profile page implemented, Modal to confirm signout is still in progress
