### ISSUE TITLE
feat: Delete Review

### ISSUE THREAD

**Issue by callumcurtis** [restauwants/restauwants#34]
### Describe the feature you'd like to request

As a user, I want to be able to delete my historical reviews, so that I can remove reviews that I don't want visible to my contacts.

### Describe the solution you'd like to see

A delete button attached to a user's own reviews that allows them to delete the review. There should be a confirmation step. Ideally, there would be a way to delete multiple reviews at once.

**Comment by Nebula5102** [comment]
Delete review fully functional

**Comment by Nebula5102** [comment]
This feature has been fully completed for a while, I began to work on the edit review feature after this, but I used the same branch. This branch has yet to be merged to main, but it was used in the demo of our presentation. Will be merged on Monday.
