### ISSUE TITLE
Decide Brand Voice, Tone, Values, and Attitude

### ISSUE THREAD

**Issue by anormananderson** [restauwants/restauwants#4]

**Comment by Nebula5102** [comment]
Worked on creating figma mockups, brand identity and new ideas. The following are my figma ideas, icon designs, and main application designs:
![Screenshot from 2024-02-16 12-07-16](https://github.com/restauwants/restauwants/assets/87686219/2438eae5-443c-4904-8e9c-8ae0891872bd)
![Screenshot from 2024-02-16 12-07-40](https://github.com/restauwants/restauwants/assets/87686219/34e79b93-7453-4038-85df-2e71a18d1bba)
![Screenshot from 2024-02-16 12-08-04](https://github.com/restauwants/restauwants/assets/87686219/234e4427-f182-47c0-b9e0-a41d663f1ff4)
![Screenshot from 2024-02-16 12-08-44](https://github.com/restauwants/restauwants/assets/87686219/7b9957a0-ada2-4712-90ca-22602ef4c334)
![Screenshot from 2024-02-16 12-09-04](https://github.com/restauwants/restauwants/assets/87686219/a6be066c-f0da-4854-b076-f3bcfab12463)
![Screenshot from 2024-02-16 12-09-23](https://github.com/restauwants/restauwants/assets/87686219/c213679d-0633-49f9-9ca7-e4dde0b0e552)
![Screenshot from 2024-02-16 12-09-50](https://github.com/restauwants/restauwants/assets/87686219/216fc07a-2e3a-4490-8b86-578201074417)

**Comment by rebecca-jeon** [comment]
I created some mock ups, logos, colour schemes, and fonts that could be used for 'RestauWant'.

colour schemes ideation:
![Screen Shot 2024-02-16 at 1 23 54 PM](https://github.com/restauwants/restauwants/assets/99245606/343f5800-4839-4d93-9f37-3a8a8658640a)
![Screen Shot 2024-02-16 at 1 24 33 PM](https://github.com/restauwants/restauwants/assets/99245606/86ebf745-aa71-4d5e-b84e-613208325936)

Logo ideation:
![Screen Shot 2024-02-16 at 1 25 12 PM](https://github.com/restauwants/restauwants/assets/99245606/86f1670a-3890-4fbe-b54e-f0eb99abc406)

Font ideation:
![Screen Shot 2024-02-16 at 1 25 34 PM](https://github.com/restauwants/restauwants/assets/99245606/3175f454-2d34-4ea3-9357-ac0b26ae9dab)

Mockups:

![Screen Shot 2024-02-16 at 1 26 13 PM](https://github.com/restauwants/restauwants/assets/99245606/dfd8b407-7b05-4729-988e-5cf6e819c2b4)
