### ISSUE TITLE
feat: Viewing Other People's Reviews

### ISSUE THREAD

**Issue by callumcurtis** [restauwants/restauwants#7]
### Describe the feature you'd like to request

As a user, I want to be able to view reviews from my friends, so that I can discover new restaurants or dishes to try.

### Describe the solution you'd like to see

A page of reviews posted by friends, ordered by descending timestamp.

**Comment by callumcurtis** [comment]
Alexander wants a way to casually discover restaurants, so that he has an alternative to word-of-mouth for his recommendations. (Created by Norman)

**Comment by callumcurtis** [comment]
Trevor wants to know people's bad experiences, so that he won't accidentally dine at those locations. (Created by Norman)

**Comment by callumcurtis** [comment]
Lily wants to know what people generally think about a place before she goes there, so the experience isn't surprising. (Created by Norman)

**Comment by callumcurtis** [comment]
Sharon wants to keep track of her friends' reviews, because she keeps their experiences in mind next time she plans to go out. (Created by Norman)

**Comment by callumcurtis** [comment]
Kevin is looking for reviews that mention price, service quality, and food quality to base his decision to visit a restaurant on. (Created by Norman)

**Comment by callumcurtis** [comment]
Jerry wants to know whether the food was worth the money, because he doesn't want to be a chump. (Created by Norman)

**Comment by Nebula5102** [comment]
Development on this feature has begun. Currently working towards the feed looking like our figma mockup:
![Screenshot from 2024-02-08 21-55-06](https://github.com/restauwants/restauwants/assets/87686219/62195ca9-ee4b-41aa-b50d-f3388d27efe2)
