### ISSUE TITLE
Work to create brand identity 

### ISSUE THREAD

**Issue by camrohwer** [restauwants/restauwants#76]
### Describe the feature you'd like to request

Develop a cohesive brand identity

### Describe the solution you'd like to see

Select a colour palette, logo, tone and brand voice

**Comment by Nebula5102** [comment]
I created a brand identity that outlines our brand voice and displays who we are as a company. The key components to all branding related to Restauwants revolves around these three adjectives: Playful, Welcoming, Creative. We want all our users to feel welcomed and like they can share their experiences as soon as they begin to use the app, from login to their first post and beyond. I made sure to relate these themes to our colour pallette and brand voice. I also created a shrimp mascot/logo which I think fits very well with our company identity!
![Screenshot from 2024-04-02 22-13-19](https://github.com/restauwants/restauwants/assets/87686219/4bd9940d-7502-4dfe-9989-7a1d1a712377)
![Screenshot from 2024-04-02 22-13-43](https://github.com/restauwants/restauwants/assets/87686219/90663bb9-eaa5-4086-89be-fa6b7a67acc8)
![Screenshot from 2024-04-02 22-14-15](https://github.com/restauwants/restauwants/assets/87686219/7893791d-2078-427b-874b-44c4bef66c77)
