### ISSUE TITLE
feat: Login

### ISSUE THREAD

**Issue by callumcurtis** [restauwants/restauwants#8]
### Describe the feature you'd like to request

As a user, I want to be able to login, so that my reviews and friends are saved to my account.

### Describe the solution you'd like to see

Create a login-wall for users to sign-in to the application before visiting the other pages in the application. Currently, auth through Discord is sufficient. In the future, we should support email + password.

**Comment by DevinFrioud** [comment]
Completed; set up login page, auth middleware.
