### ISSUE TITLE
feat: Domain Change

### ISSUE THREAD

**Issue by camrohwer** [restauwants/restauwants#87]
### Describe the feature you'd like to request

Migrate to main domain that was acquired

### Describe the solution you'd like to see

We should no longer be using the default Vercel domain for app

**Comment by callumcurtis** [comment]
Removed the `restauwants-nextjs.vercel.app` domain and registered the [www.restauwants.com](https://www.restauwants.com) domain. Updated this GitHub repo's website link to point to the new domain.

**Comment by callumcurtis** [comment]
Missing updates in the code for the new domain.
